//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace training.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductOrder
    {
        public int Order { get; set; }
        public string Product { get; set; }
        public int Count { get; set; }
    
        public virtual Order Order1 { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
